### ISSUE TITLE
"Report Problem" button next to a video

### ISSUE THREAD

**Issue by ligi** [efdevcon/devcon-website#175]
we get reports like this:
> Hi, the presentation recording of my talk on the Devcon website shows a different talk. Is there anything that we can do about it please?

but currently the barrier for reporting is quite high and so we might miss some cases. Maybe we should lower the barrier by having a button next to the video to easily report - also this can add context to the report (like the talk name in the system) to easier identify/fix the problem

**Comment by wslyvh** [comment]
We're still working on this with AV team. A more general way to provide feedback would be good, but not so keen to put up a button specifically for this. We have a good overview of 'wrong videos', which have been taken down while we work on resolving the issues. This isn't really a web/archive problem, so we should really optimize our process instead of adding these kind of buttons, imo.  

Closing, but happy to discuss further if needed.
